{"data":{"error":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","index":0,"debug":"ER_BAD_FIELD_ERROR: Unknown column 'fullname' in 'where clause'"}},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/api/user/name/c","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJjaHJpcyIsImVtYWlsIjoiY2hyaXN0b3BoZXIuanVydGhlQHp1dW1lby5jb20iLCJyb2xlcyI6WyJVc2VyIl0sInRlYW1zIjpbIlN5c3RlbV9Mb2dpc3RpayIsIlN5c3RlbV9Qcm9kdWt0aW9uIl0sImxvZ2luIjoiMjAxNy0wMy0yMVQxNTowMDowMC4wMDBaIiwiaWF0IjoxNDk5MzQ4MDI5LCJleHAiOjE0OTkzODQwMjl9.Vo1MtTxYxUyDcY4-7kcynDf4JCIH-VI54Y9GZ3hX4nA"}},"statusText":"Internal Server Error"}