{"data":{"error":{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","index":0,"debug":"ER_BAD_FIELD_ERROR: Unknown column 'order.created' in 'field list'"}},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/api/order/latest/5","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJjaHJpcyIsImVtYWlsIjoiY2hyaXN0b3BoZXIuanVydGhlQHp1dW1lby5jb20iLCJyb2xlcyI6WyJVc2VyIl0sImxvZ2luIjoiMjAxNy0wMy0yMVQxNTowMDowMC4wMDBaIiwiaWF0IjoxNDk0NTk2OTg3LCJleHAiOjE0OTQ2MzI5ODd9.UWWUgs4YTu1I0jG-gwz5UkJr3_1R3bAgJLJVntTaq68"}},"statusText":"Internal Server Error"}